CREATE TABLE "Customers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CustomerName" character varying(200) NOT NULL,
    "CustomerCode" character varying(50),
    "Address" character varying(500),
    "Email" character varying(100),
    "Phone" character varying(20),
    "Mobile" character varying(20),
    "ContactPerson" character varying(200),
    "TIN" character varying(100),
    "RegistrationNumber" character varying(100),
    "BankName" character varying(200),
    "BankAccountNumber" character varying(50),
    "Industry" character varying(500),
    "Status" character varying(50) NOT NULL,
    "PaymentTermsDays" integer NOT NULL,
    "CreditLimit" numeric NOT NULL,
    "Notes" character varying(1000),
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);


CREATE TABLE "DataProtectionKeys" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FriendlyName" text,
    "Xml" text,
    CONSTRAINT "PK_DataProtectionKeys" PRIMARY KEY ("Id")
);


CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "DisplayName" character varying(200),
    "Description" character varying(500),
    "Module" character varying(50) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);


CREATE TABLE "Requisitions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequisitionNumber" character varying(50) NOT NULL,
    "RequisitionDate" timestamp without time zone NOT NULL,
    "RequestedBy" character varying(200) NOT NULL,
    "Department" character varying(200) NOT NULL,
    "FacilityType" character varying(100) NOT NULL,
    "Purpose" character varying(500) NOT NULL,
    "EstimatedAmount" numeric(18,2) NOT NULL,
    "CostCode" character varying(50) NOT NULL,
    "BudgetCode" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "SupervisorName" character varying(200),
    "SupervisorApprovalDate" timestamp without time zone,
    "SupervisorComments" character varying(500),
    "FinanceOfficerName" character varying(200),
    "FinanceApprovalDate" timestamp without time zone,
    "FinanceComments" character varying(500),
    "BudgetApproved" boolean,
    "NeedApproved" boolean,
    "CostCodeApproved" boolean,
    "FinalApproverName" character varying(200),
    "FinalApprovalDate" timestamp without time zone,
    "FinalApproverComments" character varying(500),
    "RejectionReason" character varying(500),
    "Notes" character varying(1000),
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone,
    CONSTRAINT "PK_Requisitions" PRIMARY KEY ("Id")
);


CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "DisplayName" character varying(200),
    "Description" character varying(500),
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);


CREATE TABLE "Suppliers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SupplierName" character varying(200) NOT NULL,
    "SupplierCode" character varying(50),
    "Address" character varying(500),
    "Email" character varying(100),
    "Phone" character varying(20),
    "Mobile" character varying(20),
    "ContactPerson" character varying(200),
    "TIN" character varying(100),
    "RegistrationNumber" character varying(100),
    "BankName" character varying(200),
    "BankAccountNumber" character varying(50),
    "ProductsServices" character varying(500),
    "Status" character varying(50) NOT NULL,
    "PaymentTermsDays" integer NOT NULL,
    "Notes" character varying(1000),
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone,
    CONSTRAINT "PK_Suppliers" PRIMARY KEY ("Id")
);


CREATE TABLE "SystemSettings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SettingKey" character varying(100) NOT NULL,
    "SettingValue" character varying(500),
    "Description" character varying(200),
    "Category" character varying(50) NOT NULL,
    "ModifiedDate" timestamp without time zone NOT NULL,
    "ModifiedBy" character varying(100),
    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(100) NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Phone" character varying(20),
    "Department" character varying(100) NOT NULL,
    "Facility" character varying(100) NOT NULL,
    "FacilityType" character varying(50) NOT NULL,
    "Role" character varying(50) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "PasswordHash" character varying(256),
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone,
    "LastLoginDate" timestamp without time zone,
    "Notes" character varying(500),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "RequisitionItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RequisitionId" integer NOT NULL,
    "ItemDescription" character varying(200) NOT NULL,
    "ItemCode" character varying(100),
    "QuantityRequested" integer NOT NULL,
    "Unit" character varying(50) NOT NULL,
    "EstimatedUnitPrice" numeric(18,2) NOT NULL,
    "Justification" character varying(500),
    CONSTRAINT "PK_RequisitionItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RequisitionItems_Requisitions_RequisitionId" FOREIGN KEY ("RequisitionId") REFERENCES "Requisitions" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RolePermissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    "AssignedDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PurchaseOrders" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PONumber" character varying(50) NOT NULL,
    "PODate" timestamp without time zone NOT NULL,
    "RequisitionId" integer,
    "SupplierId" integer NOT NULL,
    "ExpectedDeliveryDate" timestamp without time zone NOT NULL,
    "DeliveryAddress" character varying(200) NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "PreparedBy" character varying(200) NOT NULL,
    "ApprovedBy" character varying(200),
    "ApprovalDate" timestamp without time zone,
    "TermsAndConditions" character varying(500),
    "Notes" character varying(1000),
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone,
    CONSTRAINT "PK_PurchaseOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseOrders_Requisitions_RequisitionId" FOREIGN KEY ("RequisitionId") REFERENCES "Requisitions" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PurchaseOrders_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "Username" character varying(100),
    "Action" character varying(100) NOT NULL,
    "Entity" character varying(100) NOT NULL,
    "EntityId" integer,
    "Details" character varying(1000),
    "ActionDate" timestamp without time zone NOT NULL,
    "IpAddress" character varying(50),
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE "UserRoles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "AssignedDate" timestamp without time zone NOT NULL,
    "AssignedBy" character varying(100),
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Invoices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceNumber" character varying(50) NOT NULL,
    "InvoiceDate" timestamp without time zone NOT NULL,
    "DueDate" timestamp without time zone NOT NULL,
    "PurchaseOrderId" integer,
    "SupplierId" integer,
    "CustomerName" character varying(200) NOT NULL,
    "CustomerAddress" character varying(500),
    "CustomerEmail" character varying(100),
    "CustomerPhone" character varying(20),
    "SubTotal" numeric NOT NULL,
    "GSTEnabled" boolean NOT NULL,
    "GSTRate" numeric NOT NULL,
    "GSTAmount" numeric NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "PaidAmount" numeric(18,2) NOT NULL,
    "Status" character varying(50) NOT NULL,
    "InvoiceType" character varying(50) NOT NULL,
    "Notes" character varying(1000),
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone,
    "CustomerId" integer,
    CONSTRAINT "PK_Invoices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Invoices_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Invoices_PurchaseOrders_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id"),
    CONSTRAINT "FK_Invoices_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id")
);


CREATE TABLE "PurchaseOrderItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PurchaseOrderId" integer NOT NULL,
    "ItemDescription" character varying(200) NOT NULL,
    "ItemCode" character varying(100),
    "QuantityOrdered" integer NOT NULL,
    "Unit" character varying(50) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "QuantityReceived" integer NOT NULL,
    "ReceivedDate" timestamp without time zone,
    CONSTRAINT "PK_PurchaseOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PurchaseOrderItems_PurchaseOrders_PurchaseOrderId" FOREIGN KEY ("PurchaseOrderId") REFERENCES "PurchaseOrders" ("Id") ON DELETE CASCADE
);


CREATE TABLE "InvoiceItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InvoiceId" integer NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_InvoiceItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InvoiceItems_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Payments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PaymentNumber" character varying(50) NOT NULL,
    "InvoiceId" integer,
    "PaymentDate" timestamp without time zone NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "PaymentMethod" character varying(50) NOT NULL,
    "ReferenceNumber" character varying(100),
    "Notes" character varying(500),
    "Purpose" character varying(500),
    "CreatedDate" timestamp without time zone NOT NULL,
    "ModifiedDate" timestamp without time zone,
    "Status" character varying(50) NOT NULL,
    "SupplierId" integer,
    "CustomerId" integer,
    "BankName" character varying(200),
    "AccountType" character varying(50),
    "BankAccountNumber" character varying(50),
    "PayeeBranchNumber" character varying(10),
    "PayeeAccountNumber" character varying(20),
    "PayerAccountNumber" character varying(50),
    "PayerBranchNumber" character varying(10),
    "PayerBankAccountNumber" character varying(20),
    "PayerName" character varying(200),
    "PayeeName" character varying(200),
    "TransferTo" character varying(200),
    "Currency" character varying(10),
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Payments_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Payments_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("Id") ON DELETE SET NULL
);


CREATE TABLE "ImportedDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileName" character varying(255) NOT NULL,
    "OriginalFileName" character varying(255) NOT NULL,
    "ContentType" character varying(100),
    "FileSize" bigint NOT NULL,
    "FileContent" bytea NOT NULL,
    "DocumentType" character varying(50) NOT NULL,
    "InvoiceId" integer,
    "PaymentId" integer,
    "ExtractedText" character varying(2000),
    "ExtractedAccountNumber" character varying(500),
    "ExtractedBankName" character varying(500),
    "ExtractedSupplierName" character varying(500),
    "ExtractedCustomerName" character varying(500),
    "ProcessingStatus" character varying(50) NOT NULL,
    "ProcessingNotes" text,
    "UploadDate" timestamp without time zone NOT NULL,
    "ProcessedDate" timestamp without time zone,
    "UploadedBy" character varying(100),
    CONSTRAINT "PK_ImportedDocuments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ImportedDocuments_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_ImportedDocuments_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE SET NULL
);


CREATE TABLE "PaymentAllocations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PaymentId" integer NOT NULL,
    "InvoiceId" integer NOT NULL,
    "AllocatedAmount" numeric(18,2) NOT NULL,
    "AllocationDate" timestamp without time zone NOT NULL,
    "Notes" character varying(500),
    CONSTRAINT "PK_PaymentAllocations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentAllocations_Invoices_InvoiceId" FOREIGN KEY ("InvoiceId") REFERENCES "Invoices" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PaymentAllocations_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");


CREATE INDEX "IX_ImportedDocuments_FileName" ON "ImportedDocuments" ("FileName");


CREATE INDEX "IX_ImportedDocuments_InvoiceId" ON "ImportedDocuments" ("InvoiceId");


CREATE INDEX "IX_ImportedDocuments_PaymentId" ON "ImportedDocuments" ("PaymentId");


CREATE INDEX "IX_InvoiceItems_InvoiceId" ON "InvoiceItems" ("InvoiceId");


CREATE INDEX "IX_Invoices_CustomerId" ON "Invoices" ("CustomerId");


CREATE UNIQUE INDEX "IX_Invoices_InvoiceNumber" ON "Invoices" ("InvoiceNumber");


CREATE INDEX "IX_Invoices_PurchaseOrderId" ON "Invoices" ("PurchaseOrderId");


CREATE INDEX "IX_Invoices_SupplierId" ON "Invoices" ("SupplierId");


CREATE INDEX "IX_PaymentAllocations_InvoiceId" ON "PaymentAllocations" ("InvoiceId");


CREATE INDEX "IX_PaymentAllocations_PaymentId_InvoiceId" ON "PaymentAllocations" ("PaymentId", "InvoiceId");


CREATE INDEX "IX_Payments_CustomerId" ON "Payments" ("CustomerId");


CREATE INDEX "IX_Payments_InvoiceId" ON "Payments" ("InvoiceId");


CREATE UNIQUE INDEX "IX_Payments_PaymentNumber" ON "Payments" ("PaymentNumber");


CREATE INDEX "IX_Payments_SupplierId" ON "Payments" ("SupplierId");


CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");


CREATE INDEX "IX_PurchaseOrderItems_PurchaseOrderId" ON "PurchaseOrderItems" ("PurchaseOrderId");


CREATE UNIQUE INDEX "IX_PurchaseOrders_PONumber" ON "PurchaseOrders" ("PONumber");


CREATE INDEX "IX_PurchaseOrders_RequisitionId" ON "PurchaseOrders" ("RequisitionId");


CREATE INDEX "IX_PurchaseOrders_SupplierId" ON "PurchaseOrders" ("SupplierId");


CREATE INDEX "IX_RequisitionItems_RequisitionId" ON "RequisitionItems" ("RequisitionId");


CREATE UNIQUE INDEX "IX_Requisitions_RequisitionNumber" ON "Requisitions" ("RequisitionNumber");


CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");


CREATE UNIQUE INDEX "IX_RolePermissions_RoleId_PermissionId" ON "RolePermissions" ("RoleId", "PermissionId");


CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");


CREATE UNIQUE INDEX "IX_Suppliers_SupplierCode" ON "Suppliers" ("SupplierCode");


CREATE UNIQUE INDEX "IX_SystemSettings_SettingKey" ON "SystemSettings" ("SettingKey");


CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");


CREATE UNIQUE INDEX "IX_UserRoles_UserId_RoleId" ON "UserRoles" ("UserId", "RoleId");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");


